/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Socket;

import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author Nhan
 */
public class EmojiPanel extends javax.swing.JPanel {

    /**
     * Creates new form EmojiPanel
     */
    public EmojiPanel() {
        initComponents();
        try {
            BufferedImage imageSSmile = ImageIO.read(new File("send.png"));
            ImageIcon icon = new ImageIcon(imageSSmile.getScaledInstance(20, 20, BufferedImage.SCALE_AREA_AVERAGING));
            btnSmile.setIcon(icon);
            
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSmile = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(7, 0));
        add(btnSmile);

        jButton26.setText("jButton26");
        add(jButton26);

        jButton27.setText("jButton26");
        add(jButton27);

        jButton28.setText("jButton26");
        add(jButton28);

        jButton29.setText("jButton26");
        add(jButton29);

        jButton30.setText("jButton26");
        add(jButton30);

        jButton31.setText("jButton26");
        add(jButton31);

        jButton32.setText("jButton26");
        add(jButton32);

        jButton33.setText("jButton26");
        add(jButton33);

        jButton34.setText("jButton26");
        add(jButton34);

        jButton35.setText("jButton26");
        add(jButton35);

        jButton36.setText("jButton26");
        add(jButton36);

        jButton37.setText("jButton26");
        add(jButton37);

        jButton38.setText("jButton26");
        add(jButton38);

        jButton39.setText("jButton26");
        add(jButton39);

        jButton40.setText("jButton26");
        add(jButton40);

        jButton41.setText("jButton26");
        add(jButton41);

        jButton42.setText("jButton26");
        add(jButton42);

        jButton43.setText("jButton26");
        add(jButton43);

        jButton44.setText("jButton26");
        add(jButton44);

        jButton45.setText("jButton26");
        add(jButton45);

        jButton46.setText("jButton26");
        add(jButton46);

        jButton47.setText("jButton26");
        add(jButton47);

        jButton48.setText("jButton26");
        add(jButton48);

        jButton49.setText("jButton26");
        add(jButton49);

        jButton50.setText("jButton26");
        add(jButton50);

        jButton51.setText("jButton26");
        add(jButton51);

        jButton52.setText("jButton26");
        add(jButton52);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSmile;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    // End of variables declaration//GEN-END:variables
}
